config/routes.rb
WbrInventory::Application.routes.draw do
  resources :customers
  root  'inventory_enter#home'
  match '/signup',  to: 'customers#new',           via: 'get'
  match '/display', to: 'inventory_enter#display', via: 'get'
  match '/lookup',  to: 'inventory_enter#lookup',  via: 'get'
  match '/edit',    to: 'inventory_enter#edit',    via: 'get'

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def show
		@customer = Customer.find(params[:id])
	end

  def new
  end
end

app/controllers/inventory_enter_controller.rb
class InventoryEnterController < ApplicationController
  
  def home
  end

  def display
  end

  def edit
  end

  def lookup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "WBR Inventory"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/inventory_enter_helper.rb
module InventoryEnterHelper
end

app/views/customers/new.html.erb
<% provide(:title, 'Create new customer')%>
<h1>Create new customer</h1>
<p>Find me in app/views/customers/new.html.erb</p>

app/views/customers/show.html.erb
<%= @customer.name %>, <%= @customer.email %>

app/views/inventory_enter/display.html.erb
<% provide(:title, "Display") %>

<h1>WBR Inventory</h1>
<p>
  This is the Display parts page for the Inventory of
  Win Brisbin Rebuilder
</p>
<%= link_to "Create new customer!", signup_path, class: "btn btn-large btn-primary" %>

app/views/inventory_enter/edit.html.erb
<% provide(:title, "Edit") %>

<h1>WBR Inventory</h1>
<p>
  This is the edit page for the Inventory of
  Win Brisbin Rebuilder
</p>
<%= link_to "Create new customer!", signup_path, class: "btn btn-large btn-primary" %>

app/views/inventory_enter/home.html.erb
<% provide(:title, "Home") %>
<div class"center hero-unit">

	<hi>WBR Inventory</h1>
	<p>
	  This is the Home Page for Win Brisbin Rebuilders.
	</p>

	<%= link_to "Create new customer!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/inventory_enter/lookup.html.erb
<% provide(:title, "Lookup") %>

<h1>WBR Inventory</h1>
<p>
  This is the lookup parts page for the Inventory of
  Win Brisbin Rebuilder
</p> 
<%= link_to "Create new customer!", signup_path, class: "btn btn-large btn-primary" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://kwikfinder.net">Lester Lookup</a>
  </small>
  <nav>
    <ul>
       <li><%= link_to "Display",   display_path %></li>
       <li><%= link_to "Lookup",    lookup_path %></li>
       <li><%= link_to "Edit",      edit_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Win Brisbin Rebuilders", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",      root_path %></li>
          <li><%= link_to "Display",   display_path %></li>
          <li><%= link_to "Lookup",    lookup_path %></li>
          <li><%= link_to "Edit",      edit_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>